version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dh202302-g2'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    #volumes:
    #  - mysql:/var/lib/mysql
# Names our volume
  mongo-container:
    image: mongo:4.4.3
    container_name: mongo-container
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: 'test'
      MONGO_INITDB_ROOT_USERNAME: 'user'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - 27018:27017
    expose:
      - 27018
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  zipkin-server-container:
    image: openzipkin/zipkin-slim
    container_name: zipkin-server-container
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    expose:
      - 9411
    depends_on:
      - storage-aux-container
  storage-aux-container:
    image: busybox:1.31.0
    container_name: storage-aux-container

  rabbitmq-container:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 15672
      - 5672
